### ISSUE TITLE
Adjust Hdman api to docker

### ISSUE THREAD

**Issue by prekucki** [golemfactory/golem-unlimited#124]
Open - starts main prcoess. (when main process ends all processes should be killed)
Close - stops main process

**Comment by prekucki** [comment]
@filipgolem pls verify

**Comment by filipgolem** [comment]
hdman.rs:
```
fn run_command(
[...]
    match command {
        Command::Open => Box::new(fut::ok("Open mock".to_string())),
        Command::Close => Box::new(fut::ok("Close mock".to_string())),
[...]
        Command::Wait => Box::new(fut::ok("Wait mock".to_string())),
[...]
```

**Comment by filipgolem** [comment]
dockerman.rs:

```
    match command {
        Command::Open => docker_man.run_for_deployment(session_id, DockerSession::do_open),
        Command::Close => docker_man.run_for_deployment(session_id, DockerSession::do_close),
[...]
        Command::Wait => docker_man.run_for_deployment(session_id, DockerSession::do_wait),
```

**Comment by filipgolem** [comment]
**Hdman**
1) **Open**: should execute main entry point.
2) **Close**: should stop all running processes.
3) If there is no main entry point, **Open** should not do anything, **Close** should still stop everything.
4) When main entry point is defined, **Open** should execute it and stop everything when main entry point stops working.
5) **Wait** should work as in DockerMan.
6) Process pool used in Wasm plugin: https://github.com/golemfactory/golem-unlimited/blob/release/0.2/gu-hdman/src/process_pool.rs

**Comment by filipgolem** [comment]
See also:
https://github.com/golemfactory/golem-unlimited/wiki/GU-Simple-exec-env-driver
