### ISSUE TITLE
Compressed upload/download suport

### ISSUE THREAD

**Issue by prekucki** [golemfactory/golem-unlimited#125]

**Comment by prekucki** [comment]
We had to change transfer mode to identity (i.e. disable compression) when transferring blobs, because actix web had compression-related bugs. Pls verify if Actix 1.0 fixes this.

**Comment by filipgolem** [comment]
When `actix-web = { version = "0.7", default-features = false }` is used (it is set to his value now), the compression is disabled.

After I added `actix-web = { version = "0.7", default-features = false, features = ["flate2"] }`, the server answers with `transfer-encoding: chunked` and `content-encoding: gzip` and everything works as expected.

Actix web 0.7.19 fixes this:
https://github.com/actix/actix-web/commit/cc6e0c6d04e868e284c45b9ec38f1cc1fe98ac39

Discussion (it should also work in 1.0):
https://github.com/actix/actix-web/issues/674

**Comment by filipgolem** [comment]
To enable sending compressed content for the gu-client, it is necessary to add e.g.: `put(url).content_encoding(actix_web::http::ContentEncoding::Gzip)`
