### ISSUE TITLE
[gu-provider] docker upload download support

### ISSUE THREAD

**Issue by prekucki** [golemfactory/golem-unlimited#126]
# Download

```json
{"downloadFile":{
  "url": "...http or https url..",
  "filePath": "...path in container where downloaded file should be extracted..",
  "format": "...raw - normal file, tar - multiple files as tar stream..",
}}
```

## Test 1

```
{"downloadFile": 
  {"url": "http://52.31.143.91/images/test.txt",
   "filePath": "/tmp/smok.txt",
   "format": "raw"
}}
```

should create file /tmp/smok.txt with "ala" text inside.

## Test 2

```
{"downloadFile": 
  {"url": "http://52.31.143.91/images/test.txt",
   "filePath": "/tmp",
   "format": "raw"
}}
```

should *fail* because file_path is a directory.

## Test 3

```
{"downloadFile": 
  {"url": "http://52.31.143.91/images/x.tar",
   "filePath": "/tmp",
   "format": "tar"
}}
```
should put extract contenst of x.tar in /tmp diractory under container.

# Upload

```json
{"uploadFile":{
  "url": "...http or https url..",
  "filePath": "...path in container..",
  "format": "...raw - normal file, tar - multiple files as tar stream..",
}}
```

## Test 1

```
{"uploadFile": 
  {"url": "http://52.31.143.91/dav/test-bash",
   "filePath": "/bin/bash",
   "format": "raw"
}}
```

should upload bash binary to http://52.31.143.91/dav/test-bash 

## Test 2

```
{"uploadFile": 
  {"url": "http://52.31.143.91/dav/test-usr-bin",
   "filePath": "/usr/bin",
   "format": "raw"
}}
```

should fail. because /usr/bin is directory

## Test 3

```
{"uploadFile": 
  {"url": "http://52.31.143.91/dav/test-usr-bin.tar",
   "filePath": "/usr/bin",
   "format": "tar"
}}
```

should upload whole /usr/bin from the container to http://52.31.143.91/dav/test-usr-bin.tar

**Comment by destruktiw** [comment]
It is implemented on feature/docker-basic branch https://github.com/golemfactory/golem-unlimited/pull/121 except for failing on Download Test 2.

Putting file in a directory path is correct docker API's operation. Checking if it is a directory on some path in container is not a trivial task.
