### ISSUE TITLE
[Web UI] {"Unknown":-1}  is displayed next to the disk status widget.

### ISSUE THREAD

**Issue by filipgolem** [golemfactory/golem-unlimited#128]
1. Run `gu-hub server run`.
2. Open `http://localhost:61622/app/index.html` in the browser.
3. There is a red label saying `{"Unknown":-1}` next to the disk status widget.

**Comment by filipgolem** [comment]
![scr](https://user-images.githubusercontent.com/44880692/51532069-75d24c00-1e3f-11e9-91dd-bd8bcb0f2cb9.png)

**Comment by filipgolem** [comment]
Also, the right margin of the whole page is wider than other margins.

**Comment by filipgolem** [comment]
On macOS (SSD) the label is `{"Unknown":-2}`.

**Comment by filipgolem** [comment]
There is a bug in the sysinfo crate (used by gu-hardware). It drops the final digits to convert partition device to disk device. It works for "sda1" -> "sda", but does not work when the partition name ends with e.g. "p1".
On Linux it is possible to get the disk device like this:
`basename $(readlink -f /sys/class/block/partition_name/..)`

**Comment by destruktiw** [comment]
I think that on mac sysinfo crate does not just cut trailing digits in a device name. Here is implementation
https://docs.rs/sysinfo/0.8.0/i686-apple-darwin/src/sysinfo/mac/system.rs.html#244-266

**Comment by filipgolem** [comment]
Yes, it doesn't work on the macOS 10.14 for some other reason (it used to work on macOS 10.13). On Linux the error is Unknown:-1 because of the trailing digits and on macOS it's Unknown:-2.
