### ISSUE TITLE
UI Plugin Manager

### ISSUE THREAD

**Issue by prekucki** [golemfactory/golem-unlimited#13]
# UI Plugin package format

ZIP file:
```
 [ / ]
  +-- gu-plugin.json
  +-- <plugin-name>
        +- app.js
        + .... other js and html files
```

gu-plugin.json
```javascript
{
  "name": "Mining", // plugin name
  "version": "0.1.0", // plugin version
  "author": "...", // plugin version
  "description": "", // plugin description
  "gu-version-req": "*", // required golem unlimited app version
  "load": [ "app.js" ] // scripts to load on startup
}
```

Other fields should be ignored. 

# Role of the plugin manager

## UC1: Plugin installation

__with running server__

```$ gu-hub plugin install Mining.zip```

1. Validate plugin package format.
2. Copy package to <work_dir>/plugins/
3. (optional) Add plugin to app config

## UC2: List installed plugins

```$ gu-hub plugin list```

Expected result is table with columns:
 * plugin - plugin name
 * version - plugin version
 * status - active, installed, error

## UC3: Uninstall a plugin

```$ gu-hub plugin uninstall Mining```

## Serving metadata

GET /app/plug -> should return array or plugin metadata

```GET /app/plug/<plugin-name>/<any-file-name>```
Should return contents of file <plugin-name>/<any-file-name> in plugin package.

Suported mime-types:
 * ```*.js``` application/json
 * ```*.html``` text/html

**Comment by Parabellum34** [comment]
hi, i cant install any plugins.
this is the error:
oot@Deathstar:/run# gu-hub plugin install golemfactory/golem-unlimited
ERROR 2020-02-12T15:34:21Z: gu_hub::plugins::rest: Cannot open "golemfactory/golem-unlimited" file

can anyone help me?
