### ISSUE TITLE
[Provider] Provider does not connect to a new hub.

### ISSUE THREAD

**Issue by filipgolem** [golemfactory/golem-unlimited#138]
1. Run `gu-provider configure` and turn on "[X] access is granted to everyone".
2. Run `gu-provider server run`.
3. Run a new hub (`gu-hub server run`).
4. gu-provider does not connect to the new hub.
5. Expectation: gu-provider connects to the new hub, even if it was started later than the provider.

**Comment by destruktiw** [comment]
This behavior is currently achievable only by `gu-provider hubs auto` command. And it is working as intended.

Maybe it should be moved to `configure` subcommand. But now `configure` is handled by PermissionModule - it looks like a tool just for groups management
