### ISSUE TITLE
A cryptic error message which starting the server, due to some file in the config directory

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/golem-unlimited#145]
```
ERROR 2019-02-07T18:04:51Z: gu_hub::server: error ! EOF while parsing a value at line 1 column 0
```
The error message is completely unclear. It probably happened after a forced reboot. The error was gone after clearing `~/.config/golemunlimited`

**Comment by destruktiw** [comment]
It's almost certainly printed out after failing to parse something to JSON. And yes, it is totally unclear
