### ISSUE TITLE
Session workspace dir is not valid path on windows

### ISSUE THREAD

**Issue by prekucki** [golemfactory/golem-unlimited#148]
.../sessions/hd\:\:21c37921-d61f-4d87-ab5f-bff1c59eeb13

char `:` is invalid filename char.

**Comment by destruktiw** [comment]
Now paths look like this:
.../sessions/hd/21c37921-d61f-4d87-ab5f-bff1c59eeb13
.../sessions/docker/2d2bdad1-d003-42ad-93a4-9d6054dacc7f
