### ISSUE TITLE
Add CONTRIBUTING.md in addition to the wiki link

### ISSUE THREAD

**Issue by kubkon** [golemfactory/golem-unlimited#153]
Just a suggestion, but perhaps it'd be worthwhile adding the content of the wiki to a standalone `CONTRIBUTING.md` file located in the project's root? AFAIK, that's the way it's done in the majority of large(r) Rust projects (e.g., [serde.rs](https://github.com/serde-rs/serde/blob/master/CONTRIBUTING.md)). This way, I would hope that people accustomed to contributing to open source projects would find it easier to navigate the golem unlimited repo and eventually help out. Let me know what you think! 😺

**Comment by destruktiw** [comment]
I don't see any drawbacks than longer files list on the main repo page. Some people might have a learned scheme of behavior that they check for Contributing.md in a root directory of a repo. So introducing your proposal would be very helpful for them.

**Comment by kubkon** [comment]
@destruktiw Awesome, glad you agree!
