### ISSUE TITLE
Different builds or configurations for admins and local users.

### ISSUE THREAD

**Issue by filipgolem** [golemfactory/golem-unlimited#169]
1. Admin version: installed from .deb, .dmg or .msi. Starts with the OS. Process not owned by local user. Its configuration is in global directories. Start/stop: system services (e.g. systemctl).
2. ~Portable version~ Local user version: configuration is saved in the home directory, process owned by local user, start/stop: UI or similar.
3. (New) Portable version: configuration is saved in the directory where the application is run (e.g. USB drive).

**Comment by filipgolem** [comment]
Ad. 1) The UI is running with local user privileges, gu-provider has its own user, so its configuration is loaded from different directory.
Ad. 2) When two different users are running gu-provider on the same machine, there could be conflicts between the processes, e.g. one of them could change hub connections of another gu-provider.

**Comment by filipgolem** [comment]
https://github.com/golemfactory/golem-unlimited/pull/221 adds support for local and global configuration directories. Use --user to use local user paths, use -c <config_dir> to set the configuration directory path.

**Comment by filipgolem** [comment]
There is a new --portable option (also active when a .gu-portable file is located in the gu-provider executable directory). In this case, the configuration is saved in the directory where the application is run (e.g. USB drive).

**Comment by prekucki** [comment]
scope reduce: Start/stop: system services on **windows**
