### ISSUE TITLE
gu-provider reports server running when it's not

### ISSUE THREAD

**Issue by tworec** [golemfactory/golem-unlimited#184]
```
vega:~$ ./gu-provider server status
Process is running (pid: 7975)
vega:~$ ./gu-provider server stop
Stopping gu-provider process (pid: 7975)
^C
vega:~$ kill 7975
-bash: kill: (7975) - No such process
vega:~$ rm .local/share/golemunlimited/
gu-provider.err  gu-provider.out  gu-provider.pid  sessions/        
vega:~$ rm .local/share/golemunlimited/gu-provider.pid 
vega:~$ ./gu-provider server status
Process is not running
```

I'd *also check* if the process with PID from file is actually running.

I suspect a similar bug in `gu-hub`

**Comment by quilir** [comment]
Status checker reports that the gu-provider process is running only when it can't acquire a file lock on the gu-provider.pid

Maybe checker had no right to lock file. Maybe some non-provider process already locked this file. Either case is super uncommon

**Comment by tworec** [comment]
`vega` is somhow creepy server. If I would encounter this again I'll leave it to show to you...
closing for now
