### ISSUE TITLE
[Provider,Windows] If temp folder does not exist provider cannot download the file

### ISSUE THREAD

**Issue by Ed-warf** [golemfactory/golem-unlimited#249]
Windows provider upon request creates var subdirectory but it doesn't automatically create folder for temporary files (tmp) so it is unable to store downloaded files thus breaks with File not found exception.

**Comment by filipgolem** [comment]
Fixed in commit 404aa5f2d45b32ef29ef90070d441d052af4614f, merged into release/0.2.
