### ISSUE TITLE
[Provider,Windows] Provider crashes when I try to access it on Golem-Hub webpage

### ISSUE THREAD

**Issue by Ed-warf** [golemfactory/golem-unlimited#251]
no sensible call stack, sorry

**Comment by Ed-warf** [comment]
It happens only on one computer so far! The other computer works flawless. If we could get debug build to now where it crashes it would be perfect

**Comment by Ed-warf** [comment]
the error is :
thread 'main' panicked at 'index 18446744073709551615 out of range for slice of length 0', src\libcore\slice\mod.rs:2569:5
which looks like 2^64-1 which means -1 for long?

**Comment by Ed-warf** [comment]
thread 'main' panicked at 'attempt to subtract with overflow', C:\Users\golem\.cargo\registry\src\github.com-1ecc6299db9ec823\sysinfo-0.5.8\src\windows\tools.rs:284:49

**Comment by Ed-warf** [comment]
https://github.com/GuillaumeGomez/sysinfo/blob/master/src/windows/tools.rs line 284

**Comment by filipgolem** [comment]
Fixed (by updating to sysinfo 0.9) in commit ba18df36a1beae8b48b953e4fb89e7404e4c8a6c, merged into release/0.2.
