### ISSUE TITLE
Allow customization of temporary folder

### ISSUE THREAD

**Issue by Ed-warf** [golemfactory/golem-unlimited#262]
This helps in situation when I've sent a bugged file with some SHA1 value and then I want to send correct one with same SHA1 value. This shouldn't influence release builds, but these situations happen during development.
The most important reason is that zipping same files several times gives different results each time (header contains a timestamp). So the SHA1 can be based on tar file but not on tar.gz file.

**Comment by filipgolem** [comment]
@Ed-warf The files should be now in the cache dir. If you are using -c option to set the config directory, please edit the dir-paths.json file in this directory and set the cacheDir field.
