### ISSUE TITLE
Invalid image URL breaks GU

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/golem-unlimited#79]
Steps to reproduce 

1. In the POST request for `CreateSession` use an invalid URL, `http://<some-ip>/app/images/monero-linux.tar.gz`
2. Then the contents of `/home/marcin/.cache/golemunlimited/images/xmr-stak.tgz` are
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```
3. Correct the URL in the POST request to  `http://<some-ip>/images/monero-linux.tar.gz`
4. Even though the URL was corrected, creating the session will fail with the message 
```
b'{"Err":{"IoError":"creating session error: Error(\\"failed to iterate over archive\\")"}}'
```

Probably, GU should not store anything in the cache if a HTTP error occurs.

**Comment by prekucki** [comment]
@tworec there are issue #57 for image hash check that should resolve this.

**Comment by tworec** [comment]
not longer occures, as session images are now standardized to have its hash
