### ISSUE TITLE
The gpu detection detects OpenCL-incapable cards

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/golem-unlimited#81]
On my laptop I have two GPUs
* an Nvidia GPU with the nouveau driver. The driver is completely incapable of OpenCL/CUDA
* an Intel GPU using the kernel-provided drivers, but I don't have the `beignet` runtime installed, so the GPU is incapable of OpenCL either

The GPU detection should probably take it into account, that some cards may not be used for computation.

```
 INFO 2018-11-10T18:00:06Z: gu_net::rpc::mock: emit=Reply("{\"Ok\":{\"gpu\":{\"amd\":0,\"nvidia\":1,\"intel\":1,\"other\":0},\"ram\":{\"free\":1940500,\"used\":6096268,\"total\":8036768},\"os\":\"Linux\",\"hostname\":\"XXXX\"}}")
```

**Comment by prekucki** [comment]
This is intended. `gu-hardware` crate just detects if there is GPU installed, and of what wendor. This work perfectly in described situation.

**Comment by marmistrz** [comment]
Then, it's probably a good idea to show something like 'driver missing' in the UI.
